### ISSUE TITLE
invalid interpolation format for networks.media-network.ipam.config.[].subnet. OMV6 Debian 11

### ISSUE THREAD

**Issue by pgk83** [navilg/media-stack#14]
Hi Guys,

Thats all i get when i try docker compse.

**invalid interpolation format for networks.media-network.ipam.config.[].subnet.
You may need to escape any $ with another $.
required variable DOCKER_SUBNET is missing a value: err**

docker-compose.env / DOCKER SUBNET configured to my docker server subnet 172.17.0.0/16

DOCKER_SUBNET=172.17.0.0/16
DOCKER_GATEWAY=172.17.0.1
LOCAL_SUBNET=10.0.0.0/16
LOCAL_DOCKER_IP=0.0.0.0

Anyone has any idea what is this?

**Comment by navilg** [comment]
Issue not reproducible
