### ISSUE TITLE
transmission username password?

### ISSUE THREAD

**Issue by Daocuong-main** [navilg/media-stack#20]
When I add Transmission to Radarr it forces me to enter username and password, but the instructions don't instruct me to create a username and password, what should I do?

**Comment by navilg** [comment]
Username and password is set thtough env variables in compose file. refer line https://github.com/navilg/media-stack/blob/09fe4f5016bdc09d101968d5b78fa1b62632ed0f/docker-compose.yml#L72C12-L72C12
Value must be changed before deploying.
