### ISSUE TITLE
Configure Radarr & Jacket 

### ISSUE THREAD

**Issue by BrunoMiguens** [navilg/media-stack#21]
The Readme refers to configuring the indexers using Jackett, however, there's no Jacket as It was removed recently.
Is this a typo?

**Comment by navilg** [comment]
Yes its typo. I missed to remove this. Jackett is now removed from compose.
Will try to fix this on weekend

**Comment by offlinehacker** [comment]
What was the reason for jackett removal? I am reading this tutorial which mentions it: https://medium.com/linux-shots/self-host-media-stack-jellyfin-radarr-sonarr-jackett-transmission-3e6a0adf716e

**Comment by navilg** [comment]
Prowlarr integrates easily and automatically with Radarr and Sonarr. Index management is also better and improving continuously on it.
Fixed document: 332954067b538fa9413851780bdca753494c6212
