### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by Hillann** [navilg/media-stack#22]
Hi

When running sudo VPN_SERVICE_PROVIDER=protonvpn OPENVPN_USER=openvpn-username OPENVPN_PASSWORD=openvpn-password SERVER_COUNTRIES=Switzerland docker compose --profile vpn up -d

I get this:

 ✘ radarr Error                                                                                                         
 ✘ jellyfin Error                                                                                                       
 ✘ vpn Error                                                                                                            
 ✘ qbittorrent Error                                                                                                   
 ✘ sonarr Error                                                                                                         
 ✘ prowlarr Error    
Error response from daemon: Get "https://lscr.io/v2/": dial tcp 3.67.33.93:443: connect: no route to host

Do you know what this is?

**Comment by navilg** [comment]
Looks like your server is behind some proxy. Try by setting proxy or unsetting the proxy (if already set).
