### ISSUE TITLE
change Jellyfin to plex? 

### ISSUE THREAD

**Issue by Hser2bio** [navilg/media-stack#25]
thanks for your job @navilg 

Is possible change Jellyfin to plex?

**Comment by Hser2bio** [comment]
change the docker from Jellyflin to plex @RageshAntonyHM

**Comment by navilg** [comment]
Why ?

**Comment by navilg** [comment]
I dont see any good reason to replace jellyfin with plex. But if anyone need plex instead of jellyfin, it can be replaced following their documents.

I try to keep stack focused on completely free and opensource tools.

@Hser2bio Though we can add a section in README for people who want to replace jellyfin with plex. If you already have the steps, You may please create a PR. I can review and merge it.

Thanks

**Comment by RageshAntonyHM** [comment]
@navilg 

Here's a brief overview of the uses for the software mentioned in the comment:







6. **Other considerations**:
   - **Lidarr**: Manages and downloads music.
   - **Navidrome**: A personal music streamer.
   - **Readarr**: Manages eBooks and audiobooks.
   - **Bazarr**: Downloads and manages subtitles for movies and TV shows.
   - **Calibre**: An eBook management system.
   - **Audiobookshelf**: Manages and streams audiobooks.
   - **Mylarr**: Similar to Sonarr and Radarr but for comics.
   - **Komga**: A server for comics and mangas.
   - **Rclone**: Tools for managing cloud storage and syncing files.
   - **Nextcloud**: A suite for file hosting and collaboration.
   - **Heimdall**: A dashboard for managing and accessing web applications more conveniently.

**Comment by Hser2bio** [comment]
> I dont see any good reason to replace jellyfin with plex. But if anyone need plex instead of jellyfin, it can be replaced following their documents.
> 
> I try to keep stack focused on completely free and opensource tools.
> 
> @Hser2bio we can add a section in README for people who want to replace jellyfin with plex. If you already have the steps, You may please create a PR. I can review and merge it.
> 
> Thanks

Morning mate, 

sorry for the delay, yeaaa

plex:
    image: lscr.io/linuxserver/plex:1.32.5
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - torrent-downloads:/downloads
    restart: unless-stopped
