### ISSUE TITLE
Why don't you use transmission anymore?

### ISSUE THREAD

**Issue by Daocuong-main** [navilg/media-stack#27]
As the title says, I see that in the old version you used both qbittorent and transmission, but now you have removed them. I followed someone else's git repo, they also left out transmission, what caused it to be removed?

**Comment by navilg** [comment]
qBittorrent has better UI than Transmission and Transmission didn't support hybrid torrent at that time. So I switched to qbt.
I try to keep the tools which I use in my homelab so that I don't have overhead of testing any tools separately.
