### ISSUE TITLE
Do not add SERVER_COUNTRIES env var when using custom VPN

### ISSUE THREAD

**Issue by beune** [navilg/media-stack#30]
I am using Wireguard custom vpn hosted on a vps I own. When adding the SERVER_COUNTRIES env var, the gluetun container only gave errors. Please add in the docker-compose a comment to not include this variable when using a custom vpn.

Other than that, great stack!  Seems to be working well.

**Comment by navilg** [comment]
@beune  Thanks for suggestion. I have made the change.
