### ISSUE TITLE
[FEATURE REQUEST] Sugestion to add on the readme 

### ISSUE THREAD

**Issue by jcebidanes** [navilg/media-stack#34]
**Is your feature request related to a problem? Please describe.**
Just using the `docker network create mynetwork` not is possible to define static ips.

error msg
```
Error response from daemon: user specified IP address is supported only when connecting to networks with user configured subnets
```

**Describe the solution you'd like**

Using this command will solve the problem `docker network create --subnet 172.20.0.0/16 mynetwork`
_This subnet is following the ip you are already using on the docker-compose.yml_

**Describe alternatives you've considered**
I tried to add subnet on the compose file but doesn't work too.

**Additional context**
I' testing only the vpn version, using nordvpn

**Comment by navilg** [comment]
fixed. Thanks
