### ISSUE TITLE
Add Overseerr to the stack as well (maybe as optional)

### ISSUE THREAD

**Issue by SpuriousGer** [navilg/media-stack#38]
**Is your feature request related to a problem? Please describe.**
No, new additional container.

**Describe the solution you'd like**
Just like the arrs, Jellyfin, etc., add Overseerr for request management as well.

**Describe alternatives you've considered**
Not aware of any alternatives.

**Additional context**
N/A

**Comment by navilg** [comment]
I do not use overseer. I will take a look and decide. I try to put what I use so that I do not have overhead of testing it separately.

**Comment by SpuriousGer** [comment]
Sorry, yes, I should have said that an alternative is sufficient, I only know Overseer, but I have no preference if it gets the job done. Thanks for considering!

**Comment by navilg** [comment]
@SpuriousGer  Overseerr is for plex ecosystem. Are you aware of any which is platform independent and works with radarr/sonarr/jellyfin without the need of plex ?

**Comment by navilg** [comment]
@SpuriousGer  Added Jellyseerr in stack. This is fork of Overseerr with support for Jellyfin (https://github.com/Fallenbagel/jellyseerr)
You may take a look and check if it works for you.

**Comment by SpuriousGer** [comment]
Excellent, thank you!
