### ISSUE TITLE
Surshark wireguard configuration has issues

### ISSUE THREAD

**Issue by vineethvijay** [navilg/media-stack#40]
I had problems with the environment variables defined in the compose with surfshark wireguard vpn.
(Seems some of the env var are not needed and it will throw errors)

Followed this https://www.smarthomebeginner.com/gluetun-docker-guide/ and all looking good now.

Btw this project is golden!!

**Comment by navilg** [comment]
WIREGUARD_ env variables in compose file is for self-hosted wireguards. You may also look into openvpn way for connecting to surfshark.

https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/surfshark.md
