### ISSUE TITLE
External drive mount

### ISSUE THREAD

**Issue by thegp13** [navilg/media-stack#42]
After deploying stack on a raspberry pi 4 with omv everything works perfectly. The only thing I found hard is how to change mount point for downloaded and presented media from one drive to another (in my example from sd card to external usb drive). It would be nice to add optional volume mount points to external drive while deploying stack. (I'm quite new with a docker and linux systems so sorry if this sounds as an easy solution).

**Comment by Dialgatrainer02** [comment]
you can change the volume mount point to where you mounted you drive eg change torrent-downloads from /opt/downloads to /mnt/drive1
