### ISSUE TITLE
Consider adding FlareSolverr for bypassing Cloudflare challenges

### ISSUE THREAD

**Issue by brycebresnan** [navilg/media-stack#48]
**Is your feature request related to a problem? Please describe.**
Some torrent aggregators utilize Cloudflare protections. FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD.
https://github.com/FlareSolverr/FlareSolverr

**Describe the solution you'd like**
Adding an optional  docker container  for FlareSolverr, which could be commented out by default.

**Describe alternatives you've considered**
I have not considered any alternatives as this tool integrates into the media stack seamlessly.

**Additional context**
I have implemented FlareSolverr into my own media-stack and it works perfectly.

**Comment by navilg** [comment]
Thanks @. Would you mind creating a PR if you already have it implemented ?

I try to keep this stack as basic and minimal needed for it to function. I can review if that would be appropriate to have in stack once we have PR.

**Comment by brycebresnan** [comment]
Absolutely! I appreciate the minimal approach. 

I can also draft up some config notes for the README for you. Mostly users can follow the instructions via the FlareSolverr repo but I did need to give it a distinct IP address inside the docker network.

**Comment by HarryBak** [comment]
> Absolutely! I appreciate the minimal approach.
> 
> I can also draft up some config notes for the README for you. Mostly users can follow the instructions via the FlareSolverr repo but I did need to give it a distinct IP address inside the docker network.

That would be awesome, I cannot get flaresolver working on my end :)

**Comment by navilg** [comment]
Closing as staled.
