### ISSUE TITLE
[FEATURE REQUEST] Make VPN Less parameterized?

### ISSUE THREAD

**Issue by jagadeesh-s2104** [navilg/media-stack#50]
**Is your feature request related to a problem? Please describe.**
I am writing to propose an enhancement to our Docker Compose setup to minimize the risk of unintentionally running our services without a VPN, which could pose significant security risks.  if a user executes docker compose up -d without specifying VPN parameters, the services start running without VPN by default. Because we all use docker and a slight mistake on our part is risky. For the first time there won't be any torrent, but in an existing setup, and if for any reason it's stopped and  you execute "docker compose up -d" which is a normal command since we use in lot of docker setup, you are going to get into trouble. 

**Describe the solution you'd like**
To mitigate this risk, I suggest introducing an explicit parameter that must be set to run the services without a VPN. This parameter could be something like runWithoutVPN=true. By requiring this parameter, we ensure that users are consciously making the decision to run without VPN, thereby reducing the likelihood of accidental exposure.

**Describe alternatives you've considered**

**Additional context**

**Comment by navilg** [comment]
This sounds good. I can add a profile name "no-vpn" for non-vpn deployment
