### ISSUE TITLE
[QUERY] custom stack

### ISSUE THREAD

**Issue by drizzt09** [navilg/media-stack#51]
> Stack include VPN, Radarr, Sonarr, Prowlarr, qBittorrent, Jellyseerr and Jellyfin.

1. I do not require VPN as I do not use one.
2. I will replace qbittorent with Rdt-Client for RD support.
3. I am using Cosmos-Cloud docker dashboard that already has it's own built-in proxy and running https successfully so I do not need Nginx.
4. Is there a way to deploy this without those 3?

**Comment by navilg** [comment]
@drizzt09 I havent used RD-client and cosmos-cloud. So I wont be able to suggest the changes. You can remove required services from docker compose file and add the required following there documents.

**Comment by drizzt09** [comment]
Oh I thought these installed as a combined container. 
Rd-client is to grab torrents through real debris services for prowlarr, sonarr, radarr to use.
