### ISSUE TITLE
[QUERY] VPN Port Forwarding

### ISSUE THREAD

**Issue by dynux90** [navilg/media-stack#55]
Hello,

i'm using proton vpn with port forwarding. When you connect with wireguard (udp) on a server it returns to you a random port to set on qbittorrent, the TORRENTING_PORT env value. because i need the torrent to be reachble under vpn.

how we can modifiy the docker compose to automate this?

**Comment by amarder** [comment]
This looks pretty good: https://codeberg.org/TechnoSam/qbittorrent-gluetun-port-update

**Comment by navilg** [comment]
This cannot be a FR as it is advanced customization which must be done by following gluetun document
